### ISSUE TITLE
User defined model colours

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2_visualiser#15]
3 options should be available per agent-state.

a) User selects a static colour.
b) User selects an agent variable of a floating point type (in the range 0-1?)  to be used to modulate the colour via hsv interpolation or any other heatmap function.
c) Similar to b, but with integer values performing a switch over discrete colour categories.

Options B and C both require runtime changes to shaders to insert bespoke colour logic.

The most extensible method for this would be for `setColor()` to take a copy of some abstract type e.g. `ColorMode`, which is able to output the requisite components to generate the features required by a shader. Extensions of this would be like `StaticColor(r,g,b)`, `HSVInterpolation(variable, min_hue, max_hue)`, with some predefined enums for common choices, and convenience methods like` setColorStatic()`.

The way forwards with this is to draft an example of how a common inserted code block could handle the 3 colour types, and what other data would need to be specified (e.g. agent variable being mapped).

If we can create a method with a common prototype, the templating becomes much easier (just cat the generated file to the shader).

**Comment by Robadob** [comment]
Currently the more technical material/lighting shaders are used ([e.g.](https://github.com/FLAMEGPU/FLAMEGPU2_visualiser/blob/master/resources/material_flat.frag)).

These detect colours based off a material in the uniform buffer. The current plan would require bypassing these (or adding some work-around). To set the diffuse (and ambient/specular/shininess/shininess strength).

The colour will need to be calculated in the vertex shader and passed to the frag shader. Without losing all the material handling, it could be possible to pass a constant between the shaders, to optimise out the material paths (and calc ambient/specular from diffuse).

**Comment by Robadob** [comment]
I've sketched out what the vertex shader Might look like here, with 3 potential inserts at the bottom. It's simply a tweaked version of [this](https://github.com/FLAMEGPU/FLAMEGPU2_visualiser/blob/master/resources/instanced_default.vert).

https://gist.github.com/Robadob/61faaa248d9ec4fd4c2c014204cf1a5a

**Comment by Robadob** [comment]
**TODO**
- [x] Mock Vertex Shader: https://gist.github.com/Robadob/61faaa248d9ec4fd4c2c014204cf1a5a
- [ ] Mock Fragment Shader
- [ ] Test that the mocked shaders work as expected (and tweak them if necessary)
- [ ] Update `Shaders` to support appending to shader source
- [ ] Update the `AgentStateConfig` and other new classes to deliver bespoke shader colour logic (and bind additional vertex attribs where necessary).

**Comment by Robadob** [comment]
It would be good to have a greater range of continuous color functions, or even dynamic palettes.

E.g. https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html
